import type {
  WorkflowApproval,
  WorkflowDefinition,
  WorkflowEvidence,
  WorkflowRuntimeData,
  WorkflowScope,
  WorkflowStep,
  WorkflowStepKind,
  WorkflowStepState,
} from "./types";

export const workflowScopes: readonly WorkflowScope[] = [
  {
    id: "menuvibes-preview",
    projectId: "menuvibes",
    tenantId: "menuvibes-preview",
    projectName: "MenuVibes",
    tenantName: "MenuVibes — vista previa",
    dataMode: "preview",
  },
  {
    id: "moneyprinter-v2-preview",
    projectId: "moneyprinter-v2",
    tenantId: "moneyprinter-v2-preview",
    projectName: "MoneyPrinterV2",
    tenantName: "MoneyPrinterV2 — vista previa",
    dataMode: "preview",
  },
  {
    id: "vivemar-preview",
    projectId: "vivemar",
    tenantId: "vivemar-preview",
    projectName: "Vivemar",
    tenantName: "Vivemar — vista previa",
    dataMode: "preview",
  },
  {
    id: "menuvibes-private-preview",
    projectId: "menuvibes-private",
    tenantId: "menuvibes-private-preview",
    projectName: "MenuVibes Private",
    tenantName: "MenuVibes Private — vista previa",
    dataMode: "preview",
  },
];

const unavailableRuntimeData: WorkflowRuntimeData = {
  availability: "unavailable",
  label: "Datos operativos no disponibles en esta vista previa",
};

function repositoryEvidence(
  workflowId: string,
  references: readonly string[],
): readonly WorkflowEvidence[] {
  return references.map((reference) => ({
    id: `${workflowId}-source-${reference
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")}`,
    label: `Archivo fuente: ${reference}`,
    kind: "repository-path",
    reference,
  }));
}

function humanApproval(
  workflowId: string,
  name: string,
  timing: WorkflowApproval["timing"],
): readonly WorkflowApproval[] {
  return [
    {
      id: `${workflowId}-human-approval`,
      name,
      timing,
      requirement: "human-required",
    },
  ];
}

function step(
  workflowId: string,
  sequence: number,
  name: string,
  kind: WorkflowStepKind,
  state: WorkflowStepState,
): WorkflowStep {
  return {
    id: `${workflowId}-${sequence}`,
    sequence,
    name,
    kind,
    state,
    owner: null,
  };
}

export const workflowFixtures: readonly WorkflowDefinition[] = [
  {
    id: "mv-tenant-onboarding",
    projectId: "menuvibes",
    tenantId: "menuvibes-preview",
    name: "Crear y publicar inquilino",
    summary: "Incorporación del inquilino y publicación de su menú.",
    domain: "Incorporación",
    externalAction: "none",
    lifecycleStatus: "implemented",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Datos del inquilino y del menú",
    output: "Menú publicado y contexto del panel del inquilino",
    steps: [
      step("mv-tenant-onboarding", 1, "Recibir datos del inquilino", "input", "unknown"),
      step("mv-tenant-onboarding", 2, "Crear el inquilino", "process", "ready"),
      step("mv-tenant-onboarding", 3, "Publicar menú y panel", "output", "ready"),
    ],
    approvals: [],
    evidence: repositoryEvidence("mv-tenant-onboarding", [
      "MenuVibes/whitelabel/dashboard.html",
      "MenuVibes/whitelabel/schema.sql",
    ]),
    gaps: [
      "La creación no es transaccional.",
      "No existe un recorrido seguro para archivar o eliminar.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mv-catalog-management",
    projectId: "menuvibes",
    tenantId: "menuvibes-preview",
    name: "Gestionar secciones y productos del menú",
    summary: "Administración del catálogo del menú para sus superficies públicas y de punto de venta.",
    domain: "Catálogo",
    externalAction: "none",
    lifecycleStatus: "implemented",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Secciones y productos del menú",
    output: "Catálogo del menú público y catálogo de punto de venta",
    steps: [
      step("mv-catalog-management", 1, "Recibir contenido del catálogo", "input", "unknown"),
      step("mv-catalog-management", 2, "Gestionar secciones y productos", "process", "ready"),
      step("mv-catalog-management", 3, "Exponer los catálogos", "output", "ready"),
    ],
    approvals: [],
    evidence: repositoryEvidence("mv-catalog-management", [
      "MenuVibes/whitelabel/dashboard.html",
      "MenuVibes/whitelabel/menu.html",
      "MenuVibes/whitelabel/schema.sql",
    ]),
    gaps: ["Se consume popularidad_menu, pero el campo no existe en el esquema."],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mv-order-operations",
    projectId: "menuvibes",
    tenantId: "menuvibes-preview",
    name: "Confirmar y operar pedidos",
    summary: "Confirmación y operación del estado de los pedidos.",
    domain: "Pedidos",
    externalAction: "none",
    lifecycleStatus: "partial",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Pedido y confirmación operativa",
    output: "Estado operativo del pedido y estado listo para el cliente",
    steps: [
      step("mv-order-operations", 1, "Recibir el pedido", "input", "unknown"),
      step("mv-order-operations", 2, "Confirmar y operar el pedido", "process", "manual"),
      step("mv-order-operations", 3, "Comunicar el estado al cliente", "output", "unknown"),
    ],
    approvals: [],
    evidence: repositoryEvidence("mv-order-operations", [
      "MenuVibes/whitelabel/mesero.html",
      "MenuVibes/whitelabel/pos.html",
      "MenuVibes/whitelabel/dashboard.html",
      "MenuVibes/whitelabel/schema.sql",
    ]),
    gaps: [
      "El punto de venta no está verificado en vivo.",
      "Existe latencia por sondeo.",
      "Los conflictos entre operadores no están gestionados.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mv-prospect-to-demo",
    projectId: "menuvibes-private",
    tenantId: "menuvibes-private-preview",
    name: "Convertir prospecto en demostración y contacto",
    summary: "Prioriza el prospecto, prepara una auditoría y una demostración, y deja el contacto sujeto a aprobación humana.",
    domain: "Prospección",
    externalAction: "outreach",
    lifecycleStatus: "partial",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Prospecto y datos para auditoría",
    output: "Lead priorizado, URL de demostración, mensaje de contacto y estado del registro",
    steps: [
      step("mv-prospect-to-demo", 1, "Recibir y auditar el prospecto", "input", "unknown"),
      step("mv-prospect-to-demo", 2, "Preparar la demostración y el mensaje", "process", "manual"),
      step("mv-prospect-to-demo", 3, "Aprobar el contacto", "approval", "manual"),
      step("mv-prospect-to-demo", 4, "Registrar el estado", "output", "unknown"),
    ],
    approvals: humanApproval(
      "mv-prospect-to-demo",
      "Aprobación humana antes del contacto",
      "before-outreach",
    ),
    evidence: repositoryEvidence("mv-prospect-to-demo", [
      "MenuVibes-private/prospectos/instagram_followers_apify.py",
      "MenuVibes-private/prospectos/vibeprospecting/build-demos-clusterA.py",
      "MenuVibes-private/prospectos/vibeprospecting/TRACKER-embudo.csv",
    ]),
    gaps: [
      "Existen esquemas duplicados para el registro.",
      "No existe una fuente única de verdad.",
      "No existe conversión de prospecto a inquilino.",
      "La entrega y las respuestas no se reconcilian.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mp-youtube-short",
    projectId: "moneyprinter-v2",
    tenantId: "moneyprinter-v2-preview",
    name: "Generar y publicar un video corto en YouTube",
    summary: "Generación de un MP4 y publicación en YouTube con aprobación humana previa.",
    domain: "Publicación social",
    externalAction: "publish",
    lifecycleStatus: "partial",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Contenido para un video corto",
    output: "Archivo MP4, URL de YouTube e historial local",
    steps: [
      step("mp-youtube-short", 1, "Recibir el contenido", "input", "unknown"),
      step("mp-youtube-short", 2, "Generar el archivo MP4", "process", "unknown"),
      step("mp-youtube-short", 3, "Aprobar la publicación", "approval", "manual"),
      step("mp-youtube-short", 4, "Publicar y guardar el resultado", "output", "unknown"),
    ],
    approvals: humanApproval(
      "mp-youtube-short",
      "Aprobación humana antes de publicar",
      "before-publish",
    ),
    evidence: repositoryEvidence("mp-youtube-short", [
      "MoneyPrinterV2/src/classes/YouTube.py",
      "MoneyPrinterV2/src/main.py",
      "MoneyPrinterV2/src/cron.py",
    ]),
    gaps: [
      "No hay recuperación por etapa, idempotencia ni prueba integral.",
      "La confirmación de carga es frágil.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mp-cross-post",
    projectId: "moneyprinter-v2",
    tenantId: "moneyprinter-v2-preview",
    name: "Publicar en varias redes mediante Post Bridge",
    summary: "Prepara solicitudes para TikTok e Instagram con aprobación humana antes de publicar.",
    domain: "Publicación social",
    externalAction: "publish",
    lifecycleStatus: "implemented",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Contenido aprobado para publicación social",
    output: "Solicitud de publicación para TikTok e Instagram",
    steps: [
      step("mp-cross-post", 1, "Recibir el contenido", "input", "unknown"),
      step("mp-cross-post", 2, "Aprobar la publicación", "approval", "manual"),
      step("mp-cross-post", 3, "Enviar la solicitud a Post Bridge", "output", "ready"),
    ],
    approvals: humanApproval(
      "mp-cross-post",
      "Aprobación humana antes de publicar",
      "before-publish",
    ),
    evidence: repositoryEvidence("mp-cross-post", [
      "MoneyPrinterV2/src/classes/PostBridge.py",
      "MoneyPrinterV2/src/post_bridge_integration.py",
      "MoneyPrinterV2/tests/test_post_bridge_client.py",
    ]),
    gaps: [
      "No existen registros locales de ejecuciones o publicaciones.",
      "No existe sondeo de estado.",
      "No existe idempotencia ni compensación.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "mp-scheduler",
    projectId: "moneyprinter-v2",
    tenantId: "moneyprinter-v2-preview",
    name: "Programar publicaciones sociales",
    summary: "Representa la programación bloqueada del proceso de publicación social.",
    domain: "Programación",
    externalAction: "publish",
    lifecycleStatus: "partial",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Trabajo de publicación programado",
    output: "Invocación bloqueada prevista de cron.py",
    steps: [
      step("mp-scheduler", 1, "Recibir el trabajo programado", "input", "unknown"),
      step("mp-scheduler", 2, "Registrar la programación", "process", "blocked"),
      step("mp-scheduler", 3, "Aprobar la publicación", "approval", "manual"),
      step("mp-scheduler", 4, "Invocar el publicador", "output", "blocked"),
    ],
    approvals: humanApproval(
      "mp-scheduler",
      "Aprobación humana antes de publicar",
      "before-publish",
    ),
    evidence: repositoryEvidence("mp-scheduler", [
      "MoneyPrinterV2/src/main.py",
      "MoneyPrinterV2/src/cron.py",
      "MoneyPrinterV2/scripts/upload_video.sh",
    ]),
    gaps: [
      "run_pending nunca se ejecuta.",
      "Los trabajos no son duraderos.",
      "El script omite el argumento de modelo requerido.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "vivemar-editorial-build",
    projectId: "vivemar",
    tenantId: "vivemar-preview",
    name: "Publicar propiedades y artículos",
    summary: "Publica páginas de propiedades y blog mediante una compilación estática.",
    domain: "Contenido editorial",
    externalAction: "none",
    lifecycleStatus: "implemented",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Contenido de propiedades y artículos",
    output: "Páginas de propiedades, blog y compilación estática",
    steps: [
      step("vivemar-editorial-build", 1, "Recibir el contenido editorial", "input", "unknown"),
      step("vivemar-editorial-build", 2, "Generar las páginas", "process", "ready"),
      step("vivemar-editorial-build", 3, "Publicar la compilación estática", "output", "ready"),
    ],
    approvals: [],
    evidence: repositoryEvidence("vivemar-editorial-build", [
      "vivemar/src/content.config.ts",
      "vivemar/src/content/propiedades",
      "vivemar/src/content/blog",
      "vivemar/src/pages/propiedades/[slug].astro",
    ]),
    gaps: [
      "No existe una interfaz unificada de creación, lectura, actualización y eliminación.",
      "El modelo de contenido está duplicado.",
    ],
    runtimeData: unavailableRuntimeData,
  },
  {
    id: "vivemar-contact",
    projectId: "vivemar",
    tenantId: "vivemar-preview",
    name: "Capturar contacto del sitio web",
    summary: "Recoge el contacto del sitio y responde con correo de lead y página de agradecimiento.",
    domain: "Captación de leads",
    externalAction: "none",
    lifecycleStatus: "implemented",
    versionStatus: "draft",
    version: "1.0.0",
    input: "Formulario de contacto del sitio web",
    output: "Correo del lead y página de agradecimiento",
    steps: [
      step("vivemar-contact", 1, "Recibir el formulario", "input", "unknown"),
      step("vivemar-contact", 2, "Enviar el correo del lead", "process", "ready"),
      step("vivemar-contact", 3, "Mostrar el agradecimiento", "output", "ready"),
    ],
    approvals: [],
    evidence: repositoryEvidence("vivemar-contact", [
      "vivemar/public/contact.php",
    ]),
    gaps: [
      "No existe un registro en CRM ni un ciclo de vida del lead.",
      "No se registra consentimiento ni atribución.",
    ],
    runtimeData: unavailableRuntimeData,
  },
];
