window.KLH_INVENTORY = [
  {
    id: "the-city-1219",
    name: "The City 1219",
    category: { es: "Estudio", en: "Studio" },
    bedrooms: "studio",
    price: 14000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/the-city-1219.jpg",
    drive: "https://drive.google.com/drive/folders/177V9pKcCom75spmSSitKZt5LSEN6jku_?usp=sharing",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "studio-playa-304",
    name: "Studio Playa 304",
    category: { es: "Estudio", en: "Studio" },
    bedrooms: "studio",
    price: 14000,
    zone: { es: "Zona por confirmar", en: "Area to be confirmed" },
    zoneKey: "confirmar",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/studio-playa-304.jpg",
    drive: "https://drive.google.com/drive/folders/15lSEj0xHAL9DpvVAQ41T7osdduGkg2gz?usp=sharing",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "singular-joy-302-sofacama",
    name: "Singular Joy 302 + Sofacama",
    category: { es: "Estudio + sofá cama", en: "Studio + sofa bed" },
    bedrooms: "studio",
    price: 18000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/singular-joy-302.jpg",
    drive: "https://drive.google.com/drive/folders/102OIalvvidgtGu4VuO84obt0QzGYC-q1?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" },
    reviewNote: { es: "Comparte carpeta con la publicación de 1 recámara en $22,000. Categoría y precio requieren confirmación.", en: "Shares its folder with the 1-bedroom listing at MXN 22,000. Category and price require confirmation." }
  },
  {
    id: "dk-exclusive-503",
    name: "DK Exclusive 503",
    category: { es: "1 recámara", en: "1 bedroom" },
    bedrooms: "1",
    price: 18000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/dk-exclusive-503.jpg",
    drive: "https://drive.google.com/drive/folders/1R8gczMuK4ZLBBuTXjSgDTa1thLiULWmk?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "singular-joy-302",
    name: "Singular Joy 302",
    category: { es: "1 recámara", en: "1 bedroom" },
    bedrooms: "1",
    price: 22000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/singular-joy-302.jpg",
    drive: "https://drive.google.com/drive/folders/102OIalvvidgtGu4VuO84obt0QzGYC-q1?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" },
    reviewNote: { es: "Comparte carpeta con la publicación de estudio + sofá cama en $18,000. Categoría y precio requieren confirmación.", en: "Shares its folder with the studio + sofa bed listing at MXN 18,000. Category and price require confirmation." }
  },
  {
    id: "horizonte-104",
    name: "Horizonte 104",
    category: { es: "1 recámara", en: "1 bedroom" },
    bedrooms: "1",
    price: 23000,
    zone: { es: "Zona por confirmar", en: "Area to be confirmed" },
    zoneKey: "confirmar",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/horizonte-104.jpg",
    drive: "https://drive.google.com/drive/folders/1w411FxJnbbJh4ZnOh0eml6mC5F3c7_4h?usp=sharing",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "the-gallery-302s",
    name: "The Gallery 302S",
    category: { es: "1 recámara", en: "1 bedroom" },
    bedrooms: "1",
    price: 23000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/the-gallery-302s.jpg",
    drive: "https://drive.google.com/drive/folders/11bEgCDqrDEQCszp62XN3rw4Svhll6YvI?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "solea-302",
    name: "Solea 302",
    category: { es: "1 recámara", en: "1 bedroom" },
    bedrooms: "1",
    price: 23000,
    zone: { es: "Zona por confirmar", en: "Area to be confirmed" },
    zoneKey: "confirmar",
    availability: "date",
    availableFrom: "2026-08-13",
    availabilityDate: "2026-08-05",
    image: "assets/properties/solea-302.jpg",
    drive: "https://drive.google.com/drive/folders/17iZ2gPaWDWCJlRsC3JeFKa_u2y8YitVz?usp=sharing",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "plaza-paraiso-i203",
    name: "Plaza Paraiso I203 · PH",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 25000,
    zone: { es: "Playacar", en: "Playacar" },
    zoneKey: "playacar",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/plaza-paraiso-i203.jpg",
    drive: "https://drive.google.com/drive/folders/1YGQvsfl7HGQrA954f6RybZrABlqdG1SI?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "the-gallery-203n",
    name: "The Gallery 203N",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 30000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/the-gallery-203n.jpg",
    drive: "https://drive.google.com/drive/folders/1DdVNhI48mNc856AMF7uAC86UdufoNKsk?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "singular-joy-214",
    name: "Singular Joy 214",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 35000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/singular-joy-214.jpg",
    drive: "https://drive.google.com/drive/folders/1vT-EytBm6Bt9s0tjfcUJGW7LM2PRetjF?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "lunada-113",
    name: "Lunada 113",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 35000,
    zone: { es: "Calle 38", en: "38th Street" },
    zoneKey: "calle38",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/lunada-113.jpg",
    drive: "https://drive.google.com/drive/folders/1PUU4GGIMDFo6988gL7kpM9dRUYJUcSmw?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "lunada-210",
    name: "Lunada 210",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 35000,
    zone: { es: "Calle 38", en: "38th Street" },
    zoneKey: "calle38",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/lunada-210.jpg",
    drive: "https://drive.google.com/drive/folders/1cTpJOa9tlUcp5MHUusHI1CNNi8m7nsuJ?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "lunada-218",
    name: "Lunada 218",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 35000,
    zone: { es: "Calle 38", en: "38th Street" },
    zoneKey: "calle38",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/lunada-218.jpg",
    drive: "https://drive.google.com/drive/folders/18JpmNwoXYqYGkfMaOtpdu4fNq5YWQw5z?usp=sharing",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  },
  {
    id: "the-city-1411",
    name: "The City 1411 · PH con piscina privada",
    category: { es: "2 recámaras", en: "2 bedrooms" },
    bedrooms: "2",
    price: 35000,
    zone: { es: "Centro", en: "Downtown" },
    zoneKey: "centro",
    availability: "now",
    availabilityDate: "2026-08-05",
    image: "assets/properties/the-city-1411.webp",
    drive: "https://drive.google.com/drive/folders/1JDcz4NZ6Kg_y_Pyuq-BJlf0weE1lzO0_?usp=drive_link",
    utility: { es: "Electricidad adicional", en: "Electricity not included" }
  }
];
